### ISSUE TITLE
Modeling taxes with high exemption thresholds

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-Core#493]
OG-USA currently uses smooth parametric functions for modeling income and wealth taxes across individuals with different income amounts.

However, a smooth function may not be the best approach for taxes with high exemption thresholds (examples of this include the [Senator Elizabeth Warren's wealth tax proposal](https://elizabethwarren.com/plans/ultra-millionaire-tax/?&mkwid=so1a1I3xB%7Cpcrid%7C374531778237%7Cpkw%7Celizabeth%20warren%7Cpmt%7Cp%7Cpdv%7Cc%7Cslid%7C%7Cproduct%7C%7Cpgrid%7C75412978223%7Cptaid%7Ckwd-171777258%7C&pgrid=75412978223&ptaid=kwd-171777258&source=WFP2019-LB-GS-SC&subsource=75412978223-elizabeth%20warren-p-374531778237&refcode=WFP2019-LB-GS-SC&refcode2=75412978223-elizabeth%20warren-p-374531778237&utm_source=Google&utm_campaign=WFP2019-LB-GS-SC&utm_term=elizabeth%20warren-374531778237&utm_medium=Search&gclid=CjwKCAjw5fzrBRASEiwAD2OSV7UBkhNTuRPJ_d58QeiJ1SCSZ7EFdGUT7147BO0oxonSllRQ25pSQBoCd44QAvD_BwE)). 

In cases like this, we might want something like the following, where `f(x)` is a smooth function:
```
if x < threshold:
    tax = 0
else:
    tax = f(x-threshold)
```

If `f(0) = 0`, I think this should still retain convex budget sets and not pose an issue for solving the model.

Thoughts @rickecon ?

**Comment by rickecon** [comment]
In summary, I think point (3) is the first best. However, I think point (4) has some significant virtues and is my most realistic in the short-term preference.

1. My fourth-place preference. A **smooth calibrated wealth tax function with a kink** at some threshold put directly into `OG-USA` model as described in @jdebacker's previous comment in this thread. Conceptually, this is the best idea because it can model the wealth tax directly and precisely. But it is also nice because we don't yet have good wealth data in the source data for the microsimulation model described in point (3). Its main drawbacks are computational. The threshold introduces a kink in the Euler equation as a function of labor supply and savings, which will make it hard to use a root finder. We would likely have to move to a minimizer, which would slow our computation times down by at least double. But this method might be worth some experimentation due to its virtues. 
2. My third-place preference. **Calibrated average wealth tax.** Similar to point (1), this option puts the wealth tax directly into the `OG-USA` model, albeit more simply. We would use a flat wealth tax rate on all levels of savings/wealth for all types of model individuals. We would calibrate that flat rate to match the revenue projected to be raised. This option is tricky because it is hard to get a good number of how much revenue a wealth tax would raise. This option also would create significantly counter factual behavioral responses by both poor and rich individuals. But it has the virtue of being computationally simple and being able to accurately replicate certain revenue levels.
3. My first-place preference, although it has its plusses and minuses. I think the smooth function approach for the wealth tax is the best way to proceed. That is, **build the wealth tax into the `Tax-Calculator` microsimulation model**, then fit parametric functions to the effective and marginal rate schedules. This will be better in terms of distributional behavioral effects than a simple calibrated average wealth tax rate, and it avoids the threshold issues with the root finder in @jdebacker's last comment in this thread that I bring up in point (1) here.
4. My second-place preference. **A hybrid option of (1) and (2).** Another option that I think is an incremental improvement on the single average wealth tax rate function from (2) is to make a single calibrated wealth tax rate for each ability type (or even each ability type and age). This approach would capture the computational simplicity of point (2) while allowing for some flexibility. If we want to put a wealth tax on the highest wealth individuals, that wealth is highly correlated with ability type. We could have seven different wealth tax rates, some of which for the lowest ability categories could be 0.
