### ISSUE TITLE
Auto-publish to PyPI

### ISSUE THREAD

**Issue by nikhilwoodruff** [PSLmodels/OG-Core#794]
E.g. with [this action](https://github.com/PolicyEngine/openfisca-us/blob/master/.github/workflows/push.yaml) (the `Publish` job)

@jdebacker FYI

**Comment by nikhilwoodruff** [comment]
@jdebacker @rickecon looks like the action didn't start for some reason

**Comment by rickecon** [comment]
@nikhilwoodruff and @jdebacker. Yes, the GH Action did not start. We need to add this to the GH Action CI tests (similar to testing whether the documents build), and we need to figure out why it is not uploading. It seems like it might have to do with the secret settings. Or maybe it is because it is bundled with the document build GH Action. Still working on this.

**Comment by jdebacker** [comment]
PR #798 resolves this.
