### ISSUE TITLE
Allow for time varying mortality and fertility

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-Core#859]
OG-Core should allow mortality and fertility rates to vary by time period.  This will allow, for example, incorporating UN population projections into country-specific calibrations.

The steps to implementing this include:
- [x] make `rho` (mortality rates) a 2D array (TxS, where T is model time period and S is model age)
  * The `"number_dims": 2` for this parameter in `default_parameters.json` (NOTE: will also need to do the same with `surv_rate`, which is just `1-rho`)
  * Update `parameters.py` to extrapolate if a user enters a 1xS vector (analogous to what is done to Deal with parameters that vary across J and over time)
  * Update all modules that use `rho` (this includes `SS.py`, `household.py`, `aggregates.py`, `TPI.py` and others

NOTE: `fert_rates` only shows up in the country-specific `demographics.py` modules - no changes to the substantive code of OG-Core for this.  BUT, the plotting functions, e.g., in `parameter_plots.py`, need to be updates to handle the new object dimensions for `rho` and `fert_rates` (and perhaps add and argument for what period (or range of time periods) one would like to plot these.

cc @prrathi

**Comment by jdebacker** [comment]
List of places to update the mortality rate parameter, `rho`,  in OG-Core:
- [ ] `household.FOC_savings`, line 406: I think this remain the same
- [ ] `household.FOC_savings`, line 456: this equation can probably stay the same
- [ ] `household.FOC_savings`, line 463: this line can probably stay the same
- [ ] `aggregates.get_BQ`, line 193:  if `method=SS` and `preTP=False`, then `p.rho` should become `p.rho[-1, :]` to pull just the SS mortality rates, if `method=SS` and `preTP=True`, then `p.rho` should become `p.rho[0, :]`**
- [ ] `aggregates.get_BQ`, lines 203 and 208: `p.rho` will be TxS so one will just need to make sure this array is reshaped appropriately for the array products that are computed here, which since it is multiplied by `pop`, which is TxS, may require no change
- [ ] `parameter_plots.plot_mort_rates`, this function will need to have an argument for the year of mortality rates to plot.  Probably best to make this a keyword argument and allow for list of years so one can easily plot how mortality rates are evolving over time.  E.g., the function definition would become `plot_mort_rates(p, years=[DEFAULT_START_YEAR], include_title=False, path=None):`

There are some other places to change in `TPI.py`, `SS.py`, and `parameters.py`, I will add these to this Issue at a later point.
cc @harisjoshi

**Comment by jdebacker** [comment]
After the above changes, we may want to add something to `parameters.py` that reshape constant mortality rates (i.e., a vector of length S) into a TxS arrays.

**Comment by harisjoshi** [comment]
Professor DeBacker,

I hope you’re doing good. Not a high priority email but just wanted to let you know that I made the changes to p.rho parameter. I’m not sure if I published it correctly to the mortrates branch but it does seem like it has been updated on github.

Best,
Hari

From: Jason DeBacker ***@***.***>
Date: Monday, June 19, 2023 at 8:36 PM
To: PSLmodels/OG-Core ***@***.***>
Cc: Joshi, Hari ***@***.***>, Mention ***@***.***>
Subject: Re: [PSLmodels/OG-Core] Allow for time varying mortality and fertility (Issue #859)

List of places to update the mortality rate parameter, rho, in OG-Core:

  *   household.FOC_savings, line 406: I think this remain the same
  *   household.FOC_savings, line 456: this equation can probably stay the same
  *   household.FOC_savings, line 463: this line can probably stay the same
  *   aggregates.get_BQ, line 193: if method=SS and preTP=False, then p.rho should become p.rho[-1, :] to pull just the SS mortality rates, if method=SS and preTP=True, then p.rho should become p.rho[0, :]**
  *   aggregates.get_BQ, lines 203 and 208: p.rho will be TxS so one will just need to make sure this array is reshaped appropriately for the array products that are computed here, which since it is multiplied by pop, which is TxS, may require no change
  *   parameter_plots.plot_mort_rates, this function will need to have an argument for the year of mortality rates to plot. Probably best to make this a keyword argument and allow for list of years so one can easily plot how mortality rates are evolving over time. E.g., the function definition would become plot_mort_rates(p, years=[DEFAULT_START_YEAR], include_title=False, path=None):

There are some other places to change in TPI.py, SS.py, and parameters.py, I will add these to this Issue at a later point.
cc @harisjoshi<https://github.com/harisjoshi>

**Comment by jdebacker** [comment]
@harisjoshi I don't see your latest changes pushed to the [harisjoshi:mortrates](https://github.com/harisjoshi/OG-Core/tree/mortrates) branch.  Can you double check that you committed and pushed these?

**Comment by harisjoshi** [comment]
@jdebacker I just committed and pushed the latest changes to the mortrates branch, they should be available to see. Apologies for the confusion.

**Comment by jdebacker** [comment]
@harisjoshi Your latest changes look great!  I think the next step is to update `parameters.py`.  I will follow up with details about that.

**Comment by jdebacker** [comment]
Resolved with PR #871
