### ISSUE TITLE
Modeling remittances

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-Core#967]
A useful addition to OG-Core would be modeling remittences, flows of outside resources that enter the economy and are directly distributed to households.

Perhaps the simplest way to model this would be to parameterize the aggregate size of remittences as a fraction of GDP:

$$ R_t = \alpha_{R,t} Y_t$$

The time varying parameter $\alpha_{R,t}$ could then be calibrated to match historical (and projected) flows of remittences.

The total remittences would the be distributed to households with household of age $s$ of type $j$ receiving remittences at time $t$ of:

$$ remit_{j,s,t} = \eta_{R,t} R_{t} $$

The $\eta_{R,t}$ is a second parameter object that defines the (exogenous) distribution of remittences across households.  This distribution could be calibrated based on micro data on receipt of remittences.

Equations that would need to be modified in the model:
1. The household budget constraint would need to be augmented to include $remit_{j,s,t}$
2. The aggregate resource constraint would need to be modified to include $R_{t}$

**Comment by rickecon** [comment]
@jdebacker. I would recommend the following change to the theory proposed above as well as a notation change.

1. I think we should label the aggregate remittances as $RM_t$, in order to not confuse it with gross interest rates (which we don't have, but are standard in macro).

2. I think the remittances should grow at a different rate than the domestic GDP. For example, [this site](https://www.statista.com/statistics/880780/philippines-value-of-remittances/) suggests that remittances have grown at rates between 16% and 3%, which do not seem correlated with Philippine growth. Rather than $RM_t = \alpha_{RM,t}Y_t$, we could assume a global economic growth rate at which the remittances grow. Or equivalently, my suggestion is to have an exogenous growth rate at which the remittances grow, which could be tied to the world GDP growth rate (or not). This way, all we need to calibrate is the initial period remittances as a percent of GDP $\alpha_{RM,0}$ and the time series of remittance growth rates $g_{RM,t}$, which allow the remittances to grow at a different rate than the country economy.

$$ RM_t = g_{RM,t}RM_{t-1} \quad\text{and}\quad RM_{0}=\alpha_{RM,0}Y_0 $$

3. I think the distribution to households is exactly right.

$$ rm_{j,s,t} = \eta_{RM,t}RM_t $$

**Comment by SeaCelo** [comment]
Some background and empirical information on determinants of remittances: [The Propensity to Remit: Macro and Micro Factors Driving Remittances to Central America and the Caribbean](https://www.elibrary.imf.org/view/journals/001/2022/203/article-A001-en.xml). Notably, the influence of the sending country's conditions dominates. 

Data source for calibration: this data and topic is tracked by the World Bank here: [Migration](https://www.worldbank.org/en/topic/migration). The data series by GDP is available in the WDI: [Personal remittances, received (% of GDP)](https://databank.worldbank.org/metadataglossary/world-development-indicators/series/BX.TRF.PWKR.DT.GD.ZS)

We already have code to access WDI data in the `macro_params.py` of `OG-ZAF` for example, so it should be simple to get this to calibrate as needed.

**Comment by rickecon** [comment]
@SeaCelo @jdebacker. Remittances are being added in PR #971 .
